### ISSUE TITLE
Replace python client with official version

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-result-validation-engine#43]
We should replace the Python client with an official version once it is stable and compatible.

What has been adjusted in your version, @Sijoma? At which point can we migrate to the official Python client?

**Comment by Sijoma** [comment]
I had some small adjustments to download the results from EURAC as this back-end does not return a proper JSON. 
https://github.com/Open-EO/openeo-wcps-driver/issues/18

This results in some workarounds in the Job Worker. 

The other changes that I made are merged upstream.

I think we can replace the client with version 0.4 back-ends.

**Comment by m-mohr** [comment]
EURAC said they'll soon return JSON. Okay, so we'll work towards 0.4 and remove it then.

**Comment by Sijoma** [comment]
The python client can be replaced after this PR https://github.com/Open-EO/openeo-python-client/pull/52 has been merged.

**Comment by m-mohr** [comment]
Has been merged. :-) What are the next steps?

**Comment by Sijoma** [comment]
That would be great! For now, I have switched the submodule to point to the official repo.
