### ISSUE TITLE
Fix the build

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-result-validation-engine#44]
The build is broken after migrating to the openEO org. We need to fix it.

**Comment by Sijoma** [comment]
Which build tools are currently used? I used Travis-CI. I could fix this if I have the credentials.

**Comment by m-mohr** [comment]
Yes, also Travis CI. Not sure how I can grant you access to Travis CI. Maybe we can fix it on Friday.

**Comment by Sijoma** [comment]
The build should be fixed now for the master branch. I am not sure about the COPERNICUS S2 vs S2_SR branch. I will take a look at it when I find the time.

**Comment by m-mohr** [comment]
The badge says 'passing', great.
